# Generated by Django 5.2.3 on 2025-07-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_shippingaddress_shipping_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_zipcode',
            field=models.CharField(max_length=255),
        ),
    ]
